package com.quick.entity;
// Generated 5 Oct, 2013 12:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;


/**
 * ForumEventDetails generated by hbm2java
 */

public class ForumEventDetails  implements java.io.Serializable {


     private int eventDetailId;
     private Date eventDate;
     private String eventDesc;
     private String eventBody;
     private String eventOwner;
     private byte[] eventImage;
     private Integer parentForumId;
     private String imageFileName;
     private String stringImage;

    public ForumEventDetails() {
    }

	
    public ForumEventDetails(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }
    public ForumEventDetails(int eventDetailId, Date eventDate, String eventDesc, String eventBody, String eventOwner, byte[] eventImage, Integer parentForumId) {
       this.eventDetailId = eventDetailId;
       this.eventDate = eventDate;
       this.eventDesc = eventDesc;
       this.eventBody = eventBody;
       this.eventOwner = eventOwner;
       this.eventImage = eventImage;
       this.parentForumId = parentForumId;
    }
   

    public int getEventDetailId() {
        return this.eventDetailId;
    }
    
    public void setEventDetailId(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }

    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }
    
    public String getEventBody() {
        return this.eventBody;
    }
    
    public void setEventBody(String eventBody) {
        this.eventBody = eventBody;
    }
    
    public String getEventOwner() {
        return this.eventOwner;
    }
    
    public void setEventOwner(String eventOwner) {
        this.eventOwner = eventOwner;
    }
    
    public byte[] getEventImage() {
        return this.eventImage;
    }
    
    public void setEventImage(byte[] eventImage) {
        this.eventImage = eventImage;
    }
    
    public Integer getParentForumId() {
        return this.parentForumId;
    }
    
    public void setParentForumId(Integer parentForumId) {
        this.parentForumId = parentForumId;
    }

    /**
     * @return the imageFileName
     */
    public String getImageFileName() {
        return imageFileName;
    }

    /**
     * @param imageFileName the imageFileName to set
     */
    public void setImageFileName(String imageFileName) {
        this.imageFileName = imageFileName;
    }
    
    
    /**
     * @return the stringImage
     */
    public String getStringImage() {
        return stringImage;
    }

    /**
     * @param stringImage the stringImage to set
     */
    public void setStringImage(String stringImage) {
        this.stringImage = stringImage;
    }
}


