package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * QualificationMaster generated by hbm2java
 */

public class QualificationMaster  implements java.io.Serializable {


     private String qualificationName;
     private Set<UserMaster> userMasters = new HashSet<UserMaster>(0);

    public QualificationMaster() {
    }

	
    public QualificationMaster(String qualificationName) {
        this.qualificationName = qualificationName;
    }
    public QualificationMaster(String qualificationName, Set<UserMaster> userMasters) {
       this.qualificationName = qualificationName;
       this.userMasters = userMasters;
    }
   
    
    public String getQualificationName() {
        return this.qualificationName;
    }
    
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }
    public Set<UserMaster> getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set<UserMaster> userMasters) {
        this.userMasters = userMasters;
    }




}


