package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RoleMaster generated by hbm2java
 */

public class RoleMaster  implements java.io.Serializable {


     private int roleId;
     private String roleName;
     private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

    public RoleMaster() {
    }

	
    public RoleMaster(int roleId, String roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public RoleMaster(int roleId, String roleName, Set<UserRoles> userRoleses) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.userRoleses = userRoleses;
    }
   
    
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }




}


