package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA

/**
 * StddivId generated by hbm2java
 */
public class StddivId  implements java.io.Serializable {


     private String std;
     private String div;

    public StddivId() {
    }

    public StddivId(String std, String div) {
       this.std = std;
       this.div = div;
    }
   

    public String getStd() {
        return this.std;
    }
    
    public void setStd(String std) {
        this.std = std;
    }

    public String getDiv() {
        return this.div;
    }
    
    public void setDiv(String div) {
        this.div = div;
    }



}


