package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA

/**
 * TeacherStddivSub generated by hbm2java
 */

public class TeacherStddivSub  implements java.io.Serializable {


     private TeacherStddivSubId id;
     private Std std;
     private UserMaster userMaster;
     private Sub sub;

    public TeacherStddivSub() {
    }

    public TeacherStddivSub(TeacherStddivSubId id, Std std, UserMaster userMaster, Sub sub) {
       this.id = id;
       this.std = std;
       this.userMaster = userMaster;
       this.sub = sub;
    }
   
    
  
    public TeacherStddivSubId getId() {
        return this.id;
    }
    
    public void setId(TeacherStddivSubId id) {
        this.id = id;
    }
    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }




}


