package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Whatsnew generated by hbm2java
 */

public class Whatsnew  implements java.io.Serializable {


     private int itemid;
     private Std std;
     private Sub sub;
     private Date releasedate;
     private String bywhom;
     private String fordiv;
     private String topic;
     private String displaynotification;

    public Whatsnew() {
    }

	
    public Whatsnew(int itemid) {
        this.itemid = itemid;
    }
    public Whatsnew(int itemid, Std std, Sub sub, Date releasedate, String bywhom, String fordiv, String topic, String displaynotification) {
       this.itemid = itemid;
       this.std = std;
       this.sub = sub;
       this.releasedate = releasedate;
       this.bywhom = bywhom;
       this.fordiv = fordiv;
       this.topic = topic;
       this.displaynotification = displaynotification;
    }
   
    
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }

    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }

    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }
  
    public Date getReleasedate() {
        return this.releasedate;
    }
    
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }
    
    public String getBywhom() {
        return this.bywhom;
    }
    
    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }
    
    public String getFordiv() {
        return this.fordiv;
    }
    
    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }
    
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    
    public String getDisplaynotification() {
        return this.displaynotification;
    }
    
    public void setDisplaynotification(String displaynotification) {
        this.displaynotification = displaynotification;
    }


}


