package com.quick.bean;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import com.quick.entity.*;
import java.util.Date;


/**
 * technology generated by hbm2java
 */

public class UpcomingTechnologyBean  implements java.io.Serializable {


     private int technologyid;
     private Std std;
     private Sub sub;
     private Date technologydate;
     private String bywhom;
     private String fordiv;
     private String technologyline;
     private String technologybody;
     private String visibletorole;

    public UpcomingTechnologyBean() {
    }

	
    public UpcomingTechnologyBean(int technologyid) {
        this.technologyid = technologyid;
    }
    public UpcomingTechnologyBean(int technologyid, Std std, Sub sub, Date technologydate, String bywhom, String fordiv, String technologyline, String technologybody, String visibletorole) {
       this.technologyid = technologyid;
       this.std = std;
       this.sub = sub;
       this.technologydate = technologydate;
       this.bywhom = bywhom;
       this.fordiv = fordiv;
       this.technologyline = technologyline;
       this.technologybody = technologybody;
       this.visibletorole = visibletorole;
    }

    public int getTechnologyid() {
        return technologyid;
    }

    public void setTechnologyid(int technologyid) {
        this.technologyid = technologyid;
    }

    public Std getStd() {
        return std;
    }

    public void setStd(Std std) {
        this.std = std;
    }

    public Sub getSub() {
        return sub;
    }

    public void setSub(Sub sub) {
        this.sub = sub;
    }

    public Date getTechnologydate() {
        return technologydate;
    }

    public void setTechnologydate(Date technologydate) {
        this.technologydate = technologydate;
    }

    public String getBywhom() {
        return bywhom;
    }

    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }

    public String getFordiv() {
        return fordiv;
    }

    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }

    public String getTechnologyline() {
        return technologyline;
    }

    public void setTechnologyline(String technologyline) {
        this.technologyline = technologyline;
    }

    public String getTechnologybody() {
        return technologybody;
    }

    public void setTechnologybody(String technologybody) {
        this.technologybody = technologybody;
    }

    public String getVisibletorole() {
        return visibletorole;
    }

    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }

}


