package com.quick.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA



/**
 * ExamStudentResponse generated by hbm2java
 */

public class ExamStudentResponse  implements java.io.Serializable {


     private ExamStudentResponseId id;
     private ExamEntry examEntry;
     private ExamQuestionsAnswers examQuestionsAnswers;
     private UserMaster userMaster;
     private String objAns;
     private String descriptiveAns;
     private int obtMarksForObjQuestion;
     private int obtMarksForDescQuestion;

    public ExamStudentResponse() {
    }

	
    public ExamStudentResponse(ExamStudentResponseId id, ExamEntry examEntry, ExamQuestionsAnswers examQuestionsAnswers, UserMaster userMaster) {
        this.id = id;
        this.examEntry = examEntry;
        this.examQuestionsAnswers = examQuestionsAnswers;
        this.userMaster = userMaster;
    }
    public ExamStudentResponse(ExamStudentResponseId id, ExamEntry examEntry, ExamQuestionsAnswers examQuestionsAnswers, UserMaster userMaster, String objAns, String descriptiveAns, int obtMarksForObjQuestion, int obtMarksForDescQuestion) {
       this.id = id;
       this.examEntry = examEntry;
       this.examQuestionsAnswers = examQuestionsAnswers;
       this.userMaster = userMaster;
       this.objAns = objAns;
       this.descriptiveAns = descriptiveAns;
       this.obtMarksForObjQuestion = obtMarksForObjQuestion;
       this.obtMarksForDescQuestion = obtMarksForDescQuestion;
    }
   
    
    public ExamStudentResponseId getId() {
        return this.id;
    }
    
    public void setId(ExamStudentResponseId id) {
        this.id = id;
    }

    public ExamEntry getExamEntry() {
        return this.examEntry;
    }
    
    public void setExamEntry(ExamEntry examEntry) {
        this.examEntry = examEntry;
    }

    public ExamQuestionsAnswers getExamQuestionsAnswers() {
        return this.examQuestionsAnswers;
    }
    
    public void setExamQuestionsAnswers(ExamQuestionsAnswers examQuestionsAnswers) {
        this.examQuestionsAnswers = examQuestionsAnswers;
    }

    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    
    public String getObjAns() {
        return this.objAns;
    }
    
    public void setObjAns(String objAns) {
        this.objAns = objAns;
    }
    
    public String getDescriptiveAns() {
        return this.descriptiveAns;
    }
    
    public void setDescriptiveAns(String descriptiveAns) {
        this.descriptiveAns = descriptiveAns;
    }
    
    public int getObtMarksForObjQuestion() {
        return this.obtMarksForObjQuestion;
    }
    
    public void setObtMarksForObjQuestion(int obtMarksForObjQuestion) {
        this.obtMarksForObjQuestion = obtMarksForObjQuestion;
    }
    
    public int getObtMarksForDescQuestion() {
        return this.obtMarksForDescQuestion;
    }
    
    public void setObtMarksForDescQuestion(int obtMarksForDescQuestion) {
        this.obtMarksForDescQuestion = obtMarksForDescQuestion;
    }




}


