package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;


/**
 * Notices generated by hbm2java
 */

public class Notices  implements java.io.Serializable {


     private int noticeid;
     private Std std;
     private Sub sub;
     private Date noticedate;
     private String bywhom;
     private String fordiv;
     private String noticeline;
     private String noticebody;
     private String visibletorole;

    public Notices() {
    }

	
    public Notices(int noticeid) {
        this.noticeid = noticeid;
    }
    public Notices(int noticeid, Std std, Sub sub, Date noticedate, String bywhom, String fordiv, String noticeline, String noticebody, String visibletorole) {
       this.noticeid = noticeid;
       this.std = std;
       this.sub = sub;
       this.noticedate = noticedate;
       this.bywhom = bywhom;
       this.fordiv = fordiv;
       this.noticeline = noticeline;
       this.noticebody = noticebody;
       this.visibletorole = visibletorole;
    }

    public int getNoticeid() {
        return this.noticeid;
    }
    
    public void setNoticeid(int noticeid) {
        this.noticeid = noticeid;
    }

    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }

    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }
   
    public Date getNoticedate() {
        return this.noticedate;
    }
    
    public void setNoticedate(Date noticedate) {
        this.noticedate = noticedate;
    }
    
   
    public String getBywhom() {
        return this.bywhom;
    }
    
    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }
    
   
    public String getFordiv() {
        return this.fordiv;
    }
    
    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }
    
   
    public String getNoticeline() {
        return this.noticeline;
    }
    
    public void setNoticeline(String noticeline) {
        this.noticeline = noticeline;
    }
    
   
    public String getNoticebody() {
        return this.noticebody;
    }
    
    public void setNoticebody(String noticebody) {
        this.noticebody = noticebody;
    }
    public String getVisibletorole() {
        return this.visibletorole;
    }
    
    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }




}


