package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Std generated by hbm2java
 */

public class Std  implements java.io.Serializable {


     private String std;
     private Set<Notices> noticeses = new HashSet<Notices>(0);
     private Set<Whoisdoingwhat> whoisdoingwhats = new HashSet<Whoisdoingwhat>(0);
     private Set<Whatsnew> whatsnews = new HashSet<Whatsnew>(0);
     private Set<TeacherStddivSub> teacherStddivSubs = new HashSet<TeacherStddivSub>(0);
     private Set<Stddiv> stddivs = new HashSet<Stddiv>(0);
     private Set<StudentMaster> studentMasters = new HashSet<StudentMaster>(0);
     private Set<UserMaster> userMasters = new HashSet<UserMaster>(0);
     private Set<Sub> subs = new HashSet<Sub>(0);

    public Std() {
    }

	
    public Std(String std) {
        this.std = std;
    }
    public Std(String std, Set<Notices> noticeses, Set<Whoisdoingwhat> whoisdoingwhats, Set<Whatsnew> whatsnews, Set<TeacherStddivSub> teacherStddivSubs, Set<Stddiv> stddivs, Set<StudentMaster> studentMasters, Set<UserMaster> userMasters, Set<Sub> subs) {
       this.std = std;
       this.noticeses = noticeses;
       this.whoisdoingwhats = whoisdoingwhats;
       this.whatsnews = whatsnews;
       this.teacherStddivSubs = teacherStddivSubs;
       this.stddivs = stddivs;
       this.studentMasters = studentMasters;
       this.userMasters = userMasters;
       this.subs = subs;
    }
   
    
    public String getStd() {
        return this.std;
    }
    
    public void setStd(String std) {
        this.std = std;
    }
    public Set<Notices> getNoticeses() {
        return this.noticeses;
    }
    
    public void setNoticeses(Set<Notices> noticeses) {
        this.noticeses = noticeses;
    }
    public Set<Whoisdoingwhat> getWhoisdoingwhats() {
        return this.whoisdoingwhats;
    }
    
    public void setWhoisdoingwhats(Set<Whoisdoingwhat> whoisdoingwhats) {
        this.whoisdoingwhats = whoisdoingwhats;
    }
    public Set<Whatsnew> getWhatsnews() {
        return this.whatsnews;
    }
    
    public void setWhatsnews(Set<Whatsnew> whatsnews) {
        this.whatsnews = whatsnews;
    }
    public Set<TeacherStddivSub> getTeacherStddivSubs() {
        return this.teacherStddivSubs;
    }
    
    public void setTeacherStddivSubs(Set<TeacherStddivSub> teacherStddivSubs) {
        this.teacherStddivSubs = teacherStddivSubs;
    }
    public Set<Stddiv> getStddivs() {
        return this.stddivs;
    }
    
    public void setStddivs(Set<Stddiv> stddivs) {
        this.stddivs = stddivs;
    }
    public Set<StudentMaster> getStudentMasters() {
        return this.studentMasters;
    }
    
    public void setStudentMasters(Set<StudentMaster> studentMasters) {
        this.studentMasters = studentMasters;
    }
    public Set<UserMaster> getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set<UserMaster> userMasters) {
        this.userMasters = userMasters;
    }

    public Set<Sub> getSubs() {
        return this.subs;
    }
    
    public void setSubs(Set<Sub> subs) {
        this.subs = subs;
    }




}


