package com.quick.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;


/**
 * StudentExamSummary generated by hbm2java
 */

public class StudentExamSummary  implements java.io.Serializable {


     private StudentExamSummaryId id;
     private ExamEntry examEntry;
     private UserMaster userMaster;
     private Date responseDt;
     private Short totalMarks;
     private Short totalObtMarksObj;
     private Short totalObtMarksDesc;
     private String result;

    public StudentExamSummary() {
    }

	
    public StudentExamSummary(StudentExamSummaryId id, ExamEntry examEntry, UserMaster userMaster) {
        this.id = id;
        this.examEntry = examEntry;
        this.userMaster = userMaster;
    }
    public StudentExamSummary(StudentExamSummaryId id, ExamEntry examEntry, UserMaster userMaster, Date responseDt, Short totalMarks, Short totalObtMarksObj, Short totalObtMarksDesc, String result) {
       this.id = id;
       this.examEntry = examEntry;
       this.userMaster = userMaster;
       this.responseDt = responseDt;
       this.totalMarks = totalMarks;
       this.totalObtMarksObj = totalObtMarksObj;
       this.totalObtMarksDesc = totalObtMarksDesc;
       this.result = result;
    }
   
    
    public StudentExamSummaryId getId() {
        return this.id;
    }
    
    public void setId(StudentExamSummaryId id) {
        this.id = id;
    }

    public ExamEntry getExamEntry() {
        return this.examEntry;
    }
    
    public void setExamEntry(ExamEntry examEntry) {
        this.examEntry = examEntry;
    }

    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
  
    public Date getResponseDt() {
        return this.responseDt;
    }
    
    public void setResponseDt(Date responseDt) {
        this.responseDt = responseDt;
    }
    
    public Short getTotalMarks() {
        return this.totalMarks;
    }
    
    public void setTotalMarks(Short totalMarks) {
        this.totalMarks = totalMarks;
    }
    
    public Short getTotalObtMarksObj() {
        return this.totalObtMarksObj;
    }
    
    public void setTotalObtMarksObj(Short totalObtMarksObj) {
        this.totalObtMarksObj = totalObtMarksObj;
    }
    
    public Short getTotalObtMarksDesc() {
        return this.totalObtMarksDesc;
    }
    
    public void setTotalObtMarksDesc(Short totalObtMarksDesc) {
        this.totalObtMarksDesc = totalObtMarksDesc;
    }
    
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }




}


