package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sub generated by hbm2java
 */

public class Sub  implements java.io.Serializable {


     private String sub;
     private Set<TeacherStddivSub> teacherStddivSubs = new HashSet<TeacherStddivSub>(0);
     private Set<Notices> noticeses = new HashSet<Notices>(0);
     private Set<Whatsnew> whatsnews = new HashSet<Whatsnew>(0);
     private Set<UserMaster> userMasters = new HashSet<UserMaster>(0);
     private Set<Std> stds = new HashSet<Std>(0);
     private Set<Whoisdoingwhat> whoisdoingwhats = new HashSet<Whoisdoingwhat>(0);

    public Sub() {
    }

	
    public Sub(String sub) {
        this.sub = sub;
    }
    public Sub(String sub, Set<TeacherStddivSub> teacherStddivSubs, Set<Notices> noticeses, Set<Whatsnew> whatsnews, Set<UserMaster> userMasters, Set<Std> stds, Set<Whoisdoingwhat> whoisdoingwhats) {
       this.sub = sub;
       this.teacherStddivSubs = teacherStddivSubs;
       this.noticeses = noticeses;
       this.whatsnews = whatsnews;
       this.userMasters = userMasters;
       this.stds = stds;
       this.whoisdoingwhats = whoisdoingwhats;
    }
   
   
    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }
    public Set<TeacherStddivSub> getTeacherStddivSubs() {
        return this.teacherStddivSubs;
    }
    
    public void setTeacherStddivSubs(Set<TeacherStddivSub> teacherStddivSubs) {
        this.teacherStddivSubs = teacherStddivSubs;
    }
    public Set<Notices> getNoticeses() {
        return this.noticeses;
    }
    
    public void setNoticeses(Set<Notices> noticeses) {
        this.noticeses = noticeses;
    }
    public Set<Whatsnew> getWhatsnews() {
        return this.whatsnews;
    }
    
    public void setWhatsnews(Set<Whatsnew> whatsnews) {
        this.whatsnews = whatsnews;
    }
    public Set<UserMaster> getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set<UserMaster> userMasters) {
        this.userMasters = userMasters;
    }
    public Set<Std> getStds() {
        return this.stds;
    }
    
    public void setStds(Set<Std> stds) {
        this.stds = stds;
    }
    public Set<Whoisdoingwhat> getWhoisdoingwhats() {
        return this.whoisdoingwhats;
    }
    
    public void setWhoisdoingwhats(Set<Whoisdoingwhat> whoisdoingwhats) {
        this.whoisdoingwhats = whoisdoingwhats;
    }




}


