package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TeacherMaster generated by hbm2java
 */

public class TeacherMaster  implements java.io.Serializable {


     private String username;
     private UserMaster userMaster;
     private Date dob;
     private Date doj;
     private Character gender;
     private String address;
     private Character isClassTeacher;
     private String ctClass;
     private String isDeleted;

    public TeacherMaster() {
    }

	
    public TeacherMaster(String username, UserMaster userMaster) {
        this.username = username;
        this.userMaster = userMaster;
    }
    public TeacherMaster(String username, UserMaster userMaster, Date dob, Date doj, Character gender, String address, Character isClassTeacher, String ctClass, String isDeleted) {
       this.username = username;
       this.userMaster = userMaster;
       this.dob = dob;
       this.doj = doj;
       this.gender = gender;
       this.address = address;
       this.isClassTeacher = isClassTeacher;
       this.ctClass = ctClass;
       this.isDeleted = isDeleted;
    }
   
    
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getDoj() {
        return this.doj;
    }
    
    public void setDoj(Date doj) {
        this.doj = doj;
    }
    
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    public Character getIsClassTeacher() {
        return this.isClassTeacher;
    }
    
    public void setIsClassTeacher(Character isClassTeacher) {
        this.isClassTeacher = isClassTeacher;
    }
    
    public String getCtClass() {
        return this.ctClass;
    }
    
    public void setCtClass(String ctClass) {
        this.ctClass = ctClass;
    }
    
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


