package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


/**
 * TeacherStddivSubId generated by hbm2java
 */
public class TeacherStddivSubId  implements java.io.Serializable {


     private String username;
     private String std;
     private String div;
     private String sub;

    public TeacherStddivSubId() {
    }

    public TeacherStddivSubId(String username, String std, String div, String sub) {
       this.username = username;
       this.std = std;
       this.div = div;
       this.sub = sub;
    }
   

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getStd() {
        return this.std;
    }
    
    public void setStd(String std) {
        this.std = std;
    }

    public String getDiv() {
        return this.div;
    }
    
    public void setDiv(String div) {
        this.div = div;
    }

    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }
  
}


