package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;


/**
 * upcoming_technology generated by hbm2java
 */



public class UpcomingTechnology  implements java.io.Serializable {

     private int technologyid;
     private String std;
     private String sub;
     private Date technologydate;
     private String bywhom;
     private String fordiv;
     private String technologyline;
     private String technologybody;
     private String visibletorole;

    public int getTechnologyid() {
        return technologyid;
    }

    public void setTechnologyid(int technologyid) {
        this.technologyid = technologyid;
    }

    public String getStd() {
        return std;
    }

    public void setStd(String std) {
        this.std = std;
    }

    public String getSub() {
        return sub;
    }

    public void setSub(String sub) {
        this.sub = sub;
    }

    public Date getTechnologydate() {
        return technologydate;
    }

    public void setTechnologydate(Date technologydate) {
        this.technologydate = technologydate;
    }

    public String getBywhom() {
        return bywhom;
    }

    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }

    public String getFordiv() {
        return fordiv;
    }

    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }

    public String getTechnologyline() {
        return technologyline;
    }

    public void setTechnologyline(String technologyline) {
        this.technologyline = technologyline;
    }

    public String getTechnologybody() {
        return technologybody;
    }

    public void setTechnologybody(String technologybody) {
        this.technologybody = technologybody;
    }

    public String getVisibletorole() {
        return visibletorole;
    }

    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }
     
     

}


