package com.quick.entity;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA

/**
 * UserRoles generated by hbm2java
 */

public class UserRoles  implements java.io.Serializable {


     private int associationId;
     private UserMaster userMaster;
     private RoleMaster roleMaster;

    public UserRoles() {
    }

    public UserRoles(int associationId, UserMaster userMaster, RoleMaster roleMaster) {
       this.associationId = associationId;
       this.userMaster = userMaster;
       this.roleMaster = roleMaster;
    }
   
    
    public int getAssociationId() {
        return this.associationId;
    }
    
    public void setAssociationId(int associationId) {
        this.associationId = associationId;
    }

    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }

    public RoleMaster getRoleMaster() {
        return this.roleMaster;
    }
    
    public void setRoleMaster(RoleMaster roleMaster) {
        this.roleMaster = roleMaster;
    }




}


